# Generated by Django 4.2.21 on 2025-05-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="skills",
            field=models.TextField(blank=True),
        ),
    ]
