# Generated by Django 4.2.21 on 2025-05-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_jobseekerprofile_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="skills",
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="skills",
            field=models.ManyToManyField(blank=True, to="core.skill"),
        ),
    ]
