# Generated by Django 4.2.21 on 2025-05-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_skill_remove_jobseekerprofile_skills_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employersubscription",
            name="start_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="job_post_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="savedjob",
            unique_together={("seeker", "job")},
        ),
    ]
