# Generated by Django 4.2.21 on 2025-05-14 04:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_employersubscription_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employersubscription",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="employersubscription",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="duration_days",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="job_post_limit",
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_jobs",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employersubscription",
            name="employer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.employerprofile"
            ),
        ),
        migrations.AlterField(
            model_name="employersubscription",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
