# Generated by Django 4.2.21 on 2025-05-14 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_payments_delete_payment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payments",
            new_name="Payment",
        ),
    ]
