# Generated by Django 4.2.21 on 2025-05-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_payments_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StaticPage",
        ),
    ]
