# Generated by Django 4.2.21 on 2025-05-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_delete_staticpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="reported_user",
        ),
        migrations.AddField(
            model_name="report",
            name="reported_job",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.job"
            ),
            preserve_default=False,
        ),
    ]
