# Generated by Django 4.2.21 on 2025-05-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_report_reported_user_report_reported_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ReportResponse",
        ),
    ]
