# Generated by Django 4.2.21 on 2025-06-14 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervidsdew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('location', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewFeedbacdsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rated', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.intervidsdew')),
            ],
        ),
        migrations.RemoveField(
            model_name='interviewfeedback',
            name='interview',
        ),
        migrations.AlterField(
            model_name='certification',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.jobseekerprofile'),
        ),
        migrations.AlterField(
            model_name='education',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='core.jobseekerprofile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='core.jobseekerprofile'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='core.jobseekerprofile'),
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='InterviewFeedback',
        ),
    ]
