# Generated by Django 4.2.21 on 2025-06-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_intervidsdew_interviewfeedbacdsk_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intervidsdew',
            new_name='Interview',
        ),
        migrations.RenameModel(
            old_name='InterviewFeedbacdsk',
            new_name='InterviewFeedback',
        ),
    ]
